name: ndef_record
description: A Dart package that provides an implementation of the NFC Data Exchange Format (NDEF).
repository: https://github.com/okadan/flutter-nfc-manager/packages/ndef_record
version: 1.2.0
resolution: workspace

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^5.0.0
