name: nfc_manager_ndef
description: A Flutter package that provides NDEF abstraction using nfc_manager plugin.
repository: https://github.com/okadan/flutter-nfc-manager/packages/nfc_manager_ndef
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  nfc_manager:

dev_dependencies:
  lints: ^5.0.0
